### ISSUE TITLE
Surface being attached endlessly

### ISSUE THREAD

**Issue by podhorsky-ksj** [Cloudef/orbment#108] opened 2015-05-19 06:07 UTC
I need to ask for some questions.

What can I use, if I'm running orbment without xorg? (WLC_XWAYLAND=0)?
Bemenu or weston terminal (run by WIN+RETURN) doesn't work.

Is there some manual for plugins or for config file, which orbment asks during the start?

Thanks.

**Comment by Cloudef** [comment] 2015-05-19 07:47
``WLC_XWAYLAND=0`` if you do have xwayland installed, if you do not have it installed, it won't be used.
Can you try weston terminal from git, usually when it does not launch, it means it's too old. Bemenu should work however. 

If these don't help, post output of the clients ran with ``WAYLAND_DEBUG=1`` env variable set.

**Comment by podhorsky-ksj** [comment] 2015-05-20 14:16
Ok, with git wayland and weston it works, thanks.

I have another issue. When this issue happen, everything freeze. I took log from orbment with enabled wlc debug and weston debug. Here is last few rows of the log:
[15:51:15.403] -> Attached surface (6) with buffer of size (1920x1080)
[15:51:15.403] -> Activity marked
[15:51:15.403] -> Commit request
[15:51:15.406] -> Interpolated idle time 1.000000 (17 : 1)
[15:51:15.406] -> Finished frame
[15:51:15.407] -> Repaint
[15:51:15.420] -> Attach request
[15:51:15.420] -> Damage request
[15:51:15.420] -> Frame request
[15:51:15.420] -> Attached surface (6) with buffer of size (1920x1080)
[15:51:15.420] -> Activity marked
[15:51:15.420] -> Commit request
[15:51:15.423] -> Interpolated idle time 1.000000 (17 : 1)
[15:51:15.423] -> Finished frame
[15:51:15.424] hit combo: <L-1> <P-1>
[15:51:15.424] -> Activity marked
[15:51:15.424] -> Repaint
[15:51:15.440] -> Interpolated idle time 1.000000 (16 : 1)
[15:51:15.440] -> Finished frame
[15:51:15.441] -> Repaint
[15:51:15.456] -> Finished frame
[15:51:15.552] hit combo: <L-1> <P-1>
[15:51:15.728] hit combo: <Super_L> <Super_L>
[15:51:16.120] hit combo: <L-Super_L> <P-Super_L>
[15:51:16.528] hit combo: <L-j> <P-j>
[15:51:16.528] -> Activity marked
[15:51:16.528] -> Repaint scheduled
[15:51:16.528] -> Attached surface (26) with buffer of size (1920x16)
[15:51:16.529] -> Attached surface (26) with buffer of size (1920x16)
[15:51:16.529] -> Attached surface (26) with buffer of size (1920x16)
[15:51:16.529] -> Attached surface (26) with buffer of size (1920x16)
[15:51:16.529] -> Attached surface (26) with buffer of size (1920x16)
[15:51:16.529] -> Attached surface (26) with buffer of size (1920x16)
[15:51:16.529] -> Attached surface (26) with buffer of size (1920x16)
[15:51:16.529] -> Attached surface (26) with buffer of size (1920x16)
[15:51:16.529] -> Attached surface (26) with buffer of size (1920x16)
[15:51:16.529] -> Attached surface (26) with buffer of size (1920x16)
[15:51:16.529] -> Attached surface (26) with buffer of size (1920x16)
[15:51:16.529] -> Attached surface (26) with buffer of size (1920x16)
[15:51:16.530] -> Attached surface (26) with buffer of size (1920x16)
[15:51:16.530] -> Attached surface (26) with buffer of size (1920x16)
[15:51:16.530] -> Attached surface (26) with buffer of size (1920x16)
[15:51:16.530] -> Attached surface (26) with buffer of size (1920x16)
[15:51:16.530] -> Attached surface (26) with buffer of size (1920x16)
[15:51:16.530] -> Attached surface (26) with buffer of size (1920x16)
[15:51:16.530] -> Attached surface (26) with buffer of size (1920x16)
[15:51:16.530] -> Attached surface (26) with buffer of size (1920x16)
[15:51:16.530] -> Attached surface (26) with buffer of size (1920x16)
[15:51:16.530] -> Attached surface (26) with buffer of size (1920x16)
....

then everything freeze and restart of pc is necessary.

I have taken log as orbment --log orbment.log > orbment-error 2>&1 and this is log from file orbment.log, so I can attach orbment-error, where seems to be very detailed messages from wayland.

Can you look at it? 
Thanks.

**Comment by Cloudef** [comment] 2015-05-20 16:20
Can you specify more closer what you did. Also full log would be preferred.

**Comment by podhorsky-ksj** [comment] 2015-05-20 20:18
I don't know exactly, what can cause this issue. I didn't do anything special. Just switching screens with LWIN+num, switching keyboard layout with LSHIFT+LALT, run application from bemenu with LWIN+P. Maybe also switching output with LWIN+L, I'm not sure if I done it this time.

Here are links to files, which I mentioned before.
https://www.dropbox.com/s/qxuh8szu38y532m/orbment-error
https://www.dropbox.com/s/3fvk33apk8ecs75/orbment.log

here is the my script for set variables and run orbment:
export GDK_BACKEND=x11
export XKB_DEFAULT_LAYOUT=us,cz
export XKB_DEFAULT_OPTIONS=grp:alt_shift_toggle,grp_led:scroll
export WLC_DEBUG=render,render-loop,focus,xwm
export WAYLAND_DEBUG=1
orbment --log orbment.log > orbment-error 2>&1 & disown

**Comment by Cloudef** [comment] 2015-05-21 07:45
It seems to keep attaching buffer endlessly at the end, that probably ends up exhausting the event loop as well, keeping orbment from repainting or handling input.

``-> Attached surface (26) with buffer of size (1920x16)`` from the size, this suspiciously looks like bemenu, however compositor should not go into this kind of state just because client does something weird.

I think this can be reproduced rather easily.

**Comment by Kinokoio** [comment] 2015-08-01 02:36
Same problem here. It seems that it has a very... strange behavior when running without xorg installed. 
Tested in Arch with and without xorg package group. Maybe there is some hidden X dependency.

**Comment by Cloudef** [comment] 2015-08-29 22:40
Is this bug still reproducable?

**Comment by podhorsky-ksj** [comment] 2015-09-14 13:02
Currently, I'm not able to reproduce this issue with newer versions of orbment.

**Comment by Cloudef** [comment] 2015-09-14 15:08
All right, I close it then.

**Closed by Cloudef** 2015-09-14 15:08 UTC
Labels: wlc
