### ISSUE TITLE
GTK+ 2.x menus don’t appear

### ISSUE THREAD

**Issue by linkmauve** [Cloudef/orbment#100] opened 2015-04-24 11:09 UTC
You can reproduce this issue with Gajim for example.

Menus are still usable at the keyboard, if you know their layout, but there is no surface being displayed.

**Comment by Cloudef** [comment] 2015-04-24 11:15
This may be duplicate of #25

**Closed** 2015-05-01 15:29 UTC
Labels: wlc

**Comment by Cloudef** [comment] 2015-05-01 19:19
Menus still randomly open to wrong place. I keep #25 open for this however.
